### ISSUE TITLE
Failed to serialize CDATASection nodes

### ISSUE THREAD

**Issue by TechQuery** [jsdom/w3c-xmlserializer#2]
## Actual

```JavaScript
const { JSDOM } = require('jsdom');

const {window: {document, XMLSerializer}} = new JSDOM();

const element = document.createElement('style'),
    documentXML = document.implementation.createDocument(null, 'xml');

element.append( documentXML.createCDATASection('a > b { }') );

console.log( (new XMLSerializer()).serializeToString( element ) );

//  InvalidStateError: Failed to serialize XML: Only Nodes and Attr objects can be serialized
```

## Expected

https://codepen.io/tech_query/pen/KrmxmQ

## Environment

```JavaScript
{ npm: '6.4.1',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.12.0',
  openssl: '1.0.2p',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.2',
  v8: '6.2.414.66',
  zlib: '1.2.11' }
```
Windows 10.0.17134.407

**Comment by domenic** [comment]
When I try to run this code in Node.js, I get a syntax error about import not being supported. Can you edit it to be valid JavaScript code that we can run and reproduce the issue?

You also deleted other important parts of the issue template, like version numbers.

We'll reopen when you've done so and confirmed that the problem still occurs.

**Comment by TechQuery** [comment]
@domenic There's no Issue template in this repository...

In my opinion, there's no relationship with ECMAScript syntax or Runtime environment about this bug. I located the code which throw this error with the Call stack's help, [`XMLSerializer` didn't take `CDATASection` into account](https://github.com/jsdom/w3c-xmlserializer/blob/7a8520d466da1d424f7369b1cad88672a74546ed/lib/serialization.js#L305)...

I think we should follow [the DOM specification](https://github.com/whatwg/dom/pull/295/files#diff-a467e681501e456ce8c1ef31425e1b41R3403)~

**Comment by domenic** [comment]
Sorry about that, I thought we were in the jsdom repository. Still, it's good practice to produce code that the people you're reporting the issue to can actually run.

**Comment by TechQuery** [comment]
@domenic How about my PR? Is there anything need to change?

**Comment by Zirro** [comment]
So... the DOM Parsing and Serialization specification which defines XMLSerializer [does not include](dfn-xml-serialization-algorithm) instructions for serializing a CDATASection node, and the main DOM specification does not supersede it by itself. While we usually follow the specifications closely, current browsers seem to serialize CDATASection nodes without issue so making an exception here may be appropriate.

@domenic, do you know if this is a case where the DOM Parsing and Serialization specification has not kept up with the main DOM specification?

**Comment by domenic** [comment]
I think this is indeed a part where DOM P&S has not kept up. @Zirro has filed https://github.com/w3c/DOM-Parsing/issues/38 for us. @TechQuery, can you add a link to https://github.com/w3c/DOM-Parsing/issues/38 in your pull request?
